#include <sys/resource.h>
#include <unistd.h>
#include "time.h"
#include "../token/token.h"
#include "./implementations/recursive.h"
#include "./implementations/non-recursive.h"
#include "../ast/ast.h"
#include "../config.h"
ASTNode *execute_recursive_descendent();
ASTNode *execute_non_recursive();
