#include "../../lex/lex.h"
#include "../../token/token.h"
#include "../errors/syntax-error.h"
#include "../../ast/ast.h"
ASTNode *handle_statement();
ASTNode *handle_program();
ASTNode *handle_expr();
ASTNode *handle_reassign_expr();
ASTNode *handle_arith_expr();
ASTNode *handle_assign_expr_list();
ASTNode *handle_arith_expr_tail();
ASTNode *handle_expr_bool_not();
ASTNode *handle_expr_bool();
ASTNode *handle_statement_structure();
ASTNode *handle_for();
ASTNode *handle_while();
ASTNode *handle_term();
ASTNode *handle_factor();
ASTNode *handle_atom();
ASTNode *handle_pow();
ASTNode *handle_if();
ASTNode *handle_compound_statement();
ASTNode *handle_expr_bool_op();
ASTNode *handle_expr_bool_rel();
ASTNode *handle_expr_bool_and();
ASTNode *handle_expr_bool_or();
ASTNode *handle_assign_expr_tail();
ASTNode *handle_items_array();
ASTNode *handle_array();
ASTNode *handle_array_atom();
ASTNode *handle_decl_expr();
ASTNode *handle_expr_bool_rel_tail();
ASTNode *handle_reassign_expr_tail();
ASTNode *handle_elseif();
ASTNode *create_node_current_token();
